[env]
PLEX_EVENTS = "media.play,media.resume,library.new"
RADARR_API_KEY = "3b489b97a8484fb9ada9aa84432a568d"
SONARR_API_KEY = "c5514464dea74fbe8f0f47feaec30ba1"
RADARR_HOST = "https://radarr.shraymonks.com"
SONARR_HOST = "https://sonarr.shraymonks.com"
