interface JellyfinApiResponse {
  Event:
    | 'Play'
    | 'Pause'
    | 'Resume'
    | 'Stop'
    | 'Scrobble'
    | 'Progress'
    | 'MarkPlayed'
    | 'MarkUnplayed'
    | 'Rate'
    | 'ItemAdded'
    | 'ItemRemoved'
    | 'ItemUpdated'
    | 'AuthenticationSucceeded'
    | 'AuthenticationFailed'
    | 'SessionStarted'
    | 'SessionEnded'
    | 'SubtitleDownloadFailure'
    | 'HasPendingRestartChanged';
  Item: {
    Name: string;
    OriginalTitle: string;
    ServerId: string;
    Id: string;
    Etag: string;
    DateCreated: string;
    CanDelete: boolean;
    CanDownload: boolean;
    HasSubtitles: boolean;
    Container: string;
    SortName: string;
    PremiereDate: string;
    ExternalUrls: object[];
    MediaSources: object[];
    Path: string;
    EnableMediaSourceDisplay: boolean;
    OfficialRating: string;
    ChannelId: null;
    Overview: string;
    Taglines: string[];
    Genres: string[];
    CommunityRating?: number;
    RunTimeTicks: number;
    PlayAccess: string;
    ProductionYear: number;
    IndexNumber?: number;
    ParentIndexNumber?: number;
    RemoteTrailers: object[];
    ProviderIds: {
      Tvdb: string;
      Imdb: string;
      Tmdb: string;
      TmdbCollection: string;
      TvRage: string;
      TvdbSlug: string;
    };
    IsHD: boolean;
    IsFolder: boolean;
    ParentId: string;
    Type: 'Episode' | 'Movie';
    People: object[];
    Studios: object[];
    GenreItems: object[];
    ParentLogoItemId?: string;
    ParentBackdropItemId?: string;
    ParentBackdropImageTags?: string[];
    LocalTrailerCount: number;
    UserData: {
      PlaybackPositionTicks: number;
      PlayCount: number;
      IsFavorite: boolean;
      LastPlayedDate?: string;
      Played: boolean;
      Key: string;
      ItemId: string;
      PlayedPercentage?: number;
      UnplayedItemCount?: number;
    };
    SeriesName: string;
    SeriesId?: string;
    SeasonId?: string;
    SpecialFeatureCount: number;
    DisplayPreferencesId: string;
    Tags: string[];
    PrimaryImageAspectRatio: number;
    SeriesPrimaryImageTag?: string;
    SeasonName?: string;
    MediaStreams: object[];
    VideoType: string;
    ImageTags: {
      Primary: string;
      Banner?: string;
      Logo?: string;
      Thumb?: string;
    };
    BackdropImageTags: string[];
    ParentLogoImageTag?: string;
    ImageBlurHashes: {
      Primary?: object;
      Logo?: object;
      Thumb?: object;
      Backdrop?: object;
      Banner?: object;
    };
    SeriesStudio?: string;
    ParentThumbItemId?: string;
    ParentThumbImageTag?: string;
    Chapters: object[];
    Trickplay: Record<string, object>;
    LocationType: string;
    MediaType: string;
    LockedFields: object[];
    LockData: boolean;
    Width: number;
    Height: number;
    CriticRating?: number;
    ProductionLocations?: string[];
    DateLastMediaAdded?: string;
    RecursiveItemCount?: number;
    ChildCount?: number;
    Status?: string;
    AirTime?: string;
    AirDays?: string[];
    EndDate?: string;
    CumulativeRunTimeTicks?: number;
  };
  User: {
    Name: string;
    ServerId: string;
    Id: string;
    HasPassword: boolean;
    HasConfiguredPassword: boolean;
    HasConfiguredEasyPassword: boolean;
    EnableAutoLogin: boolean;
    LastLoginDate: string;
    LastActivityDate: string;
    Configuration: {
      AudioLanguagePreference: string;
      PlayDefaultAudioTrack: boolean;
      SubtitleLanguagePreference: string;
      DisplayMissingEpisodes: boolean;
      GroupedFolders: object[];
      SubtitleMode: string;
      DisplayCollectionsView: boolean;
      EnableLocalPassword: boolean;
      OrderedViews: object[];
      LatestItemsExcludes: object[];
      MyMediaExcludes: object[];
      HidePlayedInLatest: boolean;
      RememberAudioSelections: boolean;
      RememberSubtitleSelections: boolean;
      EnableNextEpisodeAutoPlay: boolean;
      CastReceiverId: string;
    };
    Policy: {
      IsAdministrator: boolean;
      IsHidden: boolean;
      EnableCollectionManagement: boolean;
      EnableSubtitleManagement: boolean;
      EnableLyricManagement: boolean;
      IsDisabled: boolean;
      BlockedTags: object[];
      AllowedTags: object[];
      EnableUserPreferenceAccess: boolean;
      AccessSchedules: object[];
      BlockUnratedItems: object[];
      EnableRemoteControlOfOtherUsers: boolean;
      EnableSharedDeviceControl: boolean;
      EnableRemoteAccess: boolean;
      EnableLiveTvManagement: boolean;
      EnableLiveTvAccess: boolean;
      EnableMediaPlayback: boolean;
      EnableAudioPlaybackTranscoding: boolean;
      EnableVideoPlaybackTranscoding: boolean;
      EnablePlaybackRemuxing: boolean;
      ForceRemoteSourceTranscoding: boolean;
      EnableContentDeletion: boolean;
      EnableContentDeletionFromFolders: object[];
      EnableContentDownloading: boolean;
      EnableSyncTranscoding: boolean;
      EnableMediaConversion: boolean;
      EnabledDevices: object[];
      EnableAllDevices: boolean;
      EnabledChannels: object[];
      EnableAllChannels: boolean;
      EnabledFolders: object[];
      EnableAllFolders: boolean;
      InvalidLoginAttemptCount: number;
      LoginAttemptsBeforeLockout: number;
      MaxActiveSessions: number;
      EnablePublicSharing: boolean;
      BlockedMediaFolders: object[];
      BlockedChannels: object[];
      RemoteClientBitrateLimit: number;
      AuthenticationProviderId: string;
      PasswordResetProviderId: string;
      SyncPlayAccess: string;
    };
  };
  Server: {
    Id: string;
    Name: string;
    Version: string;
  };
  Series: {
    Name: string;
    OriginalTitle: string;
    ServerId: string;
    Id: string;
    Etag: string;
    DateCreated: string;
    DateLastMediaAdded: string;
    CanDelete: boolean;
    CanDownload: boolean;
    SortName: string;
    PremiereDate: string;
    ExternalUrls: object[];
    Path: string;
    EnableMediaSourceDisplay: boolean;
    OfficialRating: string;
    ChannelId: null;
    Overview: string;
    Taglines: object[];
    Genres: string[];
    CommunityRating: number;
    CumulativeRunTimeTicks: number;
    RunTimeTicks: number;
    PlayAccess: string;
    ProductionYear: number;
    RemoteTrailers: object[];
    ProviderIds: Record<string, string>;
    IsFolder: boolean;
    ParentId: string;
    Type: string;
    People: object[];
    Studios: object[];
    GenreItems: object[];
    LocalTrailerCount: number;
    UserData: {
      PlayedPercentage: number;
      UnplayedItemCount: number;
      PlaybackPositionTicks: number;
      PlayCount: number;
      IsFavorite: boolean;
      Played: boolean;
      Key: string;
      ItemId: string;
    };
    RecursiveItemCount: number;
    ChildCount: number;
    SpecialFeatureCount: number;
    DisplayPreferencesId: string;
    Status: string;
    AirTime: string;
    AirDays: string[];
    Tags: string[];
    PrimaryImageAspectRatio: number;
    ImageTags: Record<string, string>;
    BackdropImageTags: string[];
    ImageBlurHashes: Record<string, object>;
    LocationType: string;
    MediaType: string;
    EndDate: string;
    LockedFields: object[];
    LockData: boolean;
  };
}
